SHOW databases;

CREATE DATABASE FLIGHTS_DB;

USE FLIGHTS_DB;

SHOW TABLES;


SELECT 
    count(*) -- 693
FROM
    FLIGHTS_DB.aeropuerto_detalles_tabla;

-- TRUNCATE TABLE FLIGHTS_DB.aeropuerto_detalles_tabla;


-- DROP TABLE FLIGHTS_DB.aeropuerto_detalle;

SELECT 
    count(*) -- 483.122
FROM
    FLIGHTS_DB.aeropuerto_tabla;







-------------------------------------------------------------------------------------ANALYSIS-------------------------------------------------------------

-- DESCRIBE FLIGHTS_DB.aeropuerto_detalles_tabla;
-- DESCRIBE FLIGHTS_DB.aeropuerto_tabla;

-- #6 Determine the flights Q between 01/12/2021 and 31/01/2022


WITH RAW_DATA AS (
    SELECT
        FECHA
        ,HORAUTC
        -- ,CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP) AS DTTM_UTC
        ,FROM_UTC_TIMESTAMP(CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP), 'America/Argentina/Buenos_Aires') AS DTTM_AR -- THIS IS THE DTTM FOR THE ANALYSIS
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,AEROPUERTO
        ,ORIGEN_DESTINO
        ,CASE WHEN AEROLINEA_NOMBRE = '0' THEN NULL ELSE AEROLINEA_NOMBRE END AS AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CASE WHEN AERONAVE = '0' THEN NULL ELSE AERONAVE END AS AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        FLIGHTS_DB.aeropuerto_tabla
)
-- DEDUPLICATING EVENTS
,DEDUPLICATING_DATA AS (
    SELECT 
        *
        ,ROW_NUMBER() OVER(PARTITION BY DTTM_AR, tipo_de_movimiento,  AEROLINEA_NOMBRE, AERONAVE, AEROPUERTO, ORIGEN_DESTINO ORDER BY DTTM_AR, AEROLINEA_NOMBRE, AERONAVE) AS RNN
    FROM 
        RAW_DATA 
)
,DEDUPLICATED_RAW_DATA AS (
    SELECT 
        -- COUNT(*) -- 483.122 --> 481.858 
        *
    FROM 
        DEDUPLICATING_DATA
    WHERE 
        RNN = 1
)
SELECT 
    count(*) AS CANTIDAD_DE_VUELOS -- Q flights = 29.098
FROM 
    DEDUPLICATED_RAW_DATA
WHERE 
    tipo_de_movimiento = 'Despegue' -- Taking only the departures to take only one flew for each event.
    AND TO_DATE(DTTM_AR) BETWEEN TO_DATE('2021-12-01') AND TO_DATE('2022-01-31')
    
---- # 7
    
-- Cantidad de pasajeros que viajaron en Aerolíneas Argentinas entre el 01/01/2021 y 30/06/2022. Mostrar consulta y Resultado de la query

WITH RAW_DATA AS (
    SELECT
        FECHA
        ,HORAUTC
        -- ,CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP) AS DTTM_UTC
        ,FROM_UTC_TIMESTAMP(CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP), 'America/Argentina/Buenos_Aires') AS DTTM_AR -- THIS IS THE DTTM FOR THE ANALYSIS
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,AEROPUERTO
        ,ORIGEN_DESTINO
        ,CASE WHEN AEROLINEA_NOMBRE = '0' THEN NULL ELSE AEROLINEA_NOMBRE END AS AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CASE WHEN AERONAVE = '0' THEN NULL ELSE AERONAVE END AS AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        FLIGHTS_DB.aeropuerto_tabla
)
-- DEDUPLICATING EVENTS
,DEDUPLICATING_DATA AS (
    SELECT 
        *
        ,ROW_NUMBER() OVER(PARTITION BY DTTM_AR, tipo_de_movimiento,  AEROLINEA_NOMBRE, AERONAVE, AEROPUERTO, ORIGEN_DESTINO ORDER BY DTTM_AR, AEROLINEA_NOMBRE, AERONAVE) AS RNN
    FROM 
        RAW_DATA 
)
,DEDUPLICATED_RAW_DATA AS (
    SELECT 
        -- COUNT(*) -- 483.122 --> 481.858 
        *
    FROM 
        DEDUPLICATING_DATA
    WHERE 
        RNN = 1
)
SELECT 
    -- *
    --,SUM(PASAJEROS) OVER(PARTITION BY AEROLINEA_NOMBRE) AS TOTAL_PASAJEROS_AEROLINEAS_AR -- 3.786.547
    --,SUM(PASAJEROS) OVER(PARTITION BY FECHA, AEROLINEA_NOMBRE) AS TOTAL_PASAJEROS_AEROLINEAS_AR_BY_DAY
    SUM(PASAJEROS) AS TOTAL_PASAJEROS_AEROLINEAS_AR -- 3.786.547
FROM 
    DEDUPLICATED_RAW_DATA
WHERE 
    tipo_de_movimiento = 'Despegue' -- Taking only the departures to take only one flY for each event.
    AND TO_DATE(DTTM_AR) BETWEEN TO_DATE('2021-01-01') AND TO_DATE('2022-06-30')
    AND aerolinea_nombre = 'AEROLINEAS ARGENTINAS SA'

    
-- 8 Mostrar fecha, hora, código aeropuerto salida, ciudad de salida, código de aeropuerto de arribo, ciudad de arribo, y cantidad de pasajeros de cada vuelo, entre el 01/01/2022 y el 30/06/2022 ordenados por fecha de manera descendiente. Mostrar consulta y Resultado de la query

-- CREATED A TABLE FOR FLIGHTS WITH THE CLEANED DATA TO AVOID MANY QUERIES TO DEDUPLICATE THE ORIGINAL TABLE
-- WE CAN ADD THIS STEP HAS THE LAST STEPS INTO THE INGEST DAG. 
CREATE TABLE FLIGHTS_DB.FLIGHTS AS 
WITH RAW_DATA AS (
    SELECT
        FECHA
        ,HORAUTC
        ,CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP) AS DTTM -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,AEROPUERTO
        ,ORIGEN_DESTINO
        ,CASE WHEN AEROLINEA_NOMBRE = '0' THEN NULL ELSE AEROLINEA_NOMBRE END AS AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CASE WHEN AERONAVE = '0' THEN NULL ELSE AERONAVE END AS AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        FLIGHTS_DB.aeropuerto_tabla
)
-- DEDUPLICATING EVENTS
,DEDUPLICATING_DATA AS (
    SELECT 
        *
        ,ROW_NUMBER() OVER(PARTITION BY DTTM, tipo_de_movimiento,  AEROLINEA_NOMBRE, AERONAVE, AEROPUERTO, ORIGEN_DESTINO ORDER BY DTTM, AEROLINEA_NOMBRE, AERONAVE) AS RNN
    FROM 
        RAW_DATA 
)
SELECT 
    -- COUNT(*) -- 483.122 --> 481.858 
    *
FROM 
    DEDUPLICATING_DATA
WHERE 
    RNN = 1;
    
----------------------------------

WITH RAW_AIRPORTS_DATA AS (
    SELECT 
        AEROPUERTO -- PK
        ,OAC -- Oceanic Area Control
        ,IATA -- IATA airport's code
        ,TIPO
        ,DENOMINACION
        ,COORDENADAS 
        ,LATITUD
        ,LONGITUD 
        ,ELEV -- ELEVATION
        ,UOM_ELEV -- ELEVATION'S UNITS
        ,REF -- CITY
        ,DISTANCIA_REF -- DISTANCE FROM THE REFERENCE
        ,DIRECCION_REF -- ORIENTATION FRIN THE REFERENCE
        ,CONDICION
        ,REGION
        ,USO
        ,TRAFICO
        ,SNA
        ,CONCESIONADO
        ,PROVINCIA
    FROM 
        FLIGHTS_DB.aeropuerto_detalles_tabla
)
SELECT 
    *
FROM
    RAW_AIRPORTS_DATA 
WHERE 
    aeropuerto IS NULL
    
--- #8  Mostrar fecha, hora, código aeropuerto salida, ciudad de salida, código de aeropuerto de arribo, ciudad de arribo, y cantidad de pasajeros de cada vuelo, entre el 01/01/2022 y el 30/06/2022 ordenados por fecha de manera descendiente. 
-- Mostrar consulta y Resultado de la query    

WITH RAW_DATA AS (
    SELECT
        FECHA
        ,HORAUTC
        ,CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP) AS DTTM_UTC
        ,FROM_UTC_TIMESTAMP(CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP), 'America/Argentina/Buenos_Aires') AS DTTM_AR -- THIS IS THE DTTM FOR THE ANALYSIS
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,AEROPUERTO
        ,ORIGEN_DESTINO
        ,CASE WHEN AEROLINEA_NOMBRE = '0' THEN NULL ELSE AEROLINEA_NOMBRE END AS AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CASE WHEN AERONAVE = '0' THEN NULL ELSE AERONAVE END AS AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        FLIGHTS_DB.aeropuerto_tabla
)
-- DEDUPLICATING EVENTS
,DEDUPLICATING_DATA AS (
    SELECT 
        *
        ,ROW_NUMBER() OVER(PARTITION BY DTTM_AR, tipo_de_movimiento,  AEROLINEA_NOMBRE, AERONAVE, AEROPUERTO, ORIGEN_DESTINO ORDER BY DTTM_AR, AEROLINEA_NOMBRE, AERONAVE) AS RNN
    FROM 
        RAW_DATA 
    WHERE 
        -- FILTERING BY DATE BEFORE, TO AVOID HEAVY JOINS
        TO_DATE(DTTM_AR) BETWEEN TO_DATE('2022-01-01') AND TO_DATE('2022-06-30')
)
,FLIGHTS_EVENTS AS (
    SELECT 
        -- COUNT(*) -- 483.122 --> 481.858 
        *
    FROM 
        DEDUPLICATING_DATA
    WHERE 
        RNN = 1
) 
/*
SELECT 
    COUNT(*) -- 189.597
FROM 
    FLIGHTS_EVENTS
*/
-- HERE 'HDO' SEEMS TO BE AN ISSUE IN THE IMPUT DATA, THERE IS 1 ROW WITH NOT MATCHED AIRPORT'S DATA AND HAS THIS AIRPORT = 'HDO'
,ADD_ORIGIN_AIRPORT_DETAILS AS ( 
    SELECT 
        FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,TO_DATE(FE.DTTM_AR) AS FECHA
        ,DATE_FORMAT(FE.DTTM_AR, 'HH:mm') AS HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO AS AEROPUERTO_ORIGEN
        ,O.AEROPUERTO AS AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,O.iata AS ORIGEN_IATA
        ,O.REF AS CIUDAD_ORIGEN
        ,FE.ORIGEN_DESTINO AS AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        --,D.IATA
        --,D.REF AS CIUDAD_DESTINO
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        FLIGHTS_EVENTS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla O
            ON O.aeropuerto = FE.AEROPUERTO 
)
/*
SELECT
    *
FROM 
    ADD_ORIGIN_AIRPORT_DETAILS
WHERE
    aeropuerto_ORIGEN_CODE IS NULL -- 1/189.597 IT ISN'T SIGNIFICANT
*/
,ADD_DESTINATION_AIRPORT_DETAILS AS (
    SELECT 
        FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,FE.FECHA
        ,FE.HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO_ORIGEN
        ,FE.AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,FE.ORIGEN_IATA
        ,FE.CIUDAD_ORIGEN
        ,FE.AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,D.AEROPUERTO AS AEROPUERTO_DESTINO_CODE
        ,D.IATA AS DESTINO_IATA
        ,D.REF AS CIUDAD_DESTINO
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        ADD_ORIGIN_AIRPORT_DETAILS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla D
            ON D.aeropuerto = FE.AEROPUERTO_DESTINO
)
/*
SELECT 
    COUNT(*) 
    --DISTINCT 
    --    aeropuerto_DESTINO
FROM 
    ADD_DESTINATION_AIRPORT_DETAILS
WHERE
    AEROPUERTO_DESTINO_CODE IS NULL -- 567/189.597 --> 0.3% NOT AN IMPORTANT IMPACT
*/
SELECT 
    -- DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
    FECHA
    ,HORA
    ,CASE WHEN ORIGEN_IATA IS NULL THEN AEROPUERTO_ORIGEN ELSE ORIGEN_IATA END AS CODIGO_AEROPUERTO_SALIDA
    ,CIUDAD_ORIGEN AS CIUDAD_DE_SALIDA
    ,CASE WHEN DESTINO_IATA IS NULL THEN AEROPUERTO_DESTINO ELSE DESTINO_IATA END AS CODIGO_AEROPUERTO_ARRIBO -- TODO: LET SEE IF THIS IS THE IATA CODE
    ,CIUDAD_DESTINO AS CIUDAD_DE_ARRIBO
    ,PASAJEROS
FROM 
    ADD_DESTINATION_AIRPORT_DETAILS
ORDER BY
    FECHA DESC
    
            
-------------------------------

    
    
--- # 9 CREATE A TABLE WITH THE CLEANED DATA FOR VISUALIZATION
-- 
--
-- DROP TABLE flights_db.DOMESTIC_FLIGHTS_DATA;
    
    
-- CREATE TABLE flights_db.DOMESTIC_FLIGHTS_DATA AS 
WITH RAW_DATA AS (
    SELECT
        FECHA
        ,HORAUTC
        ,CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP) AS DTTM_UTC
        ,FROM_UTC_TIMESTAMP(CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP), 'America/Argentina/Buenos_Aires') AS DTTM_AR -- THIS IS THE DTTM FOR THE ANALYSIS
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,AEROPUERTO
        ,ORIGEN_DESTINO
        ,CASE WHEN AEROLINEA_NOMBRE = '0' THEN NULL ELSE AEROLINEA_NOMBRE END AS AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CASE WHEN AERONAVE = '0' THEN NULL ELSE AERONAVE END AS AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        FLIGHTS_DB.aeropuerto_tabla
)
-- DEDUPLICATING EVENTS
,DEDUPLICATING_DATA AS (
    SELECT 
        *
        ,ROW_NUMBER() OVER(PARTITION BY DTTM_AR, tipo_de_movimiento,  AEROLINEA_NOMBRE, AERONAVE, AEROPUERTO, ORIGEN_DESTINO ORDER BY DTTM_AR, AEROLINEA_NOMBRE, AERONAVE) AS RNN
    FROM 
        RAW_DATA 
    WHERE 
        TO_DATE(DTTM_AR) BETWEEN TO_DATE('2021-01-01') AND TO_DATE('2022-06-30')
)
,FLIGHTS_EVENTS AS (
    SELECT 
        *
    FROM 
        DEDUPLICATING_DATA
    WHERE 
        RNN = 1
) 
,ADD_ORIGIN_AIRPORT_DETAILS AS ( 
    SELECT
        FE.DTTM_UTC
        ,FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,TO_DATE(FE.DTTM_AR) AS FECHA
        ,DATE_FORMAT(FE.DTTM_AR, 'HH:mm') AS HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO AS AEROPUERTO_ORIGEN
        ,O.AEROPUERTO AS AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,O.iata AS ORIGEN_IATA
        ,O.REF AS CIUDAD_ORIGEN
        ,FE.ORIGEN_DESTINO AS AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        FLIGHTS_EVENTS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla O
            ON O.aeropuerto = FE.AEROPUERTO 
)
,ADD_DESTINATION_AIRPORT_DETAILS AS (
    SELECT
        FE.DTTM_UTC
        ,FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,FE.FECHA
        ,FE.HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO_ORIGEN
        ,FE.AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,FE.ORIGEN_IATA
        ,FE.CIUDAD_ORIGEN
        ,FE.AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,D.AEROPUERTO AS AEROPUERTO_DESTINO_CODE
        ,D.IATA AS DESTINO_IATA
        ,D.REF AS CIUDAD_DESTINO
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        ADD_ORIGIN_AIRPORT_DETAILS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla D
            ON D.aeropuerto = FE.AEROPUERTO_DESTINO
)
,DOMESTIC_FLIGHTS_DATA AS (
    SELECT 
        DTTM_UTC
        ,DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,FECHA AS FECHA_AR
        ,HORA AS HORA_AR
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,CASE WHEN ORIGEN_IATA IS NULL THEN AEROPUERTO_ORIGEN ELSE ORIGEN_IATA END AS CODIGO_AEROPUERTO_SALIDA
        ,CIUDAD_ORIGEN AS CIUDAD_DE_SALIDA
        ,CASE WHEN DESTINO_IATA IS NULL THEN AEROPUERTO_DESTINO ELSE DESTINO_IATA END AS CODIGO_AEROPUERTO_ARRIBO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,CIUDAD_DESTINO AS CIUDAD_DE_ARRIBO
        ,AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        ADD_DESTINATION_AIRPORT_DETAILS
)
,TOP_TEN_AIR_COMPANIES AS (
    SELECT
        AEROLINEA_NOMBRE
        ,SUM(PASAJEROS) AS TOTAL_PASENGERS
    FROM    
        DOMESTIC_FLIGHTS_DATA
    WHERE
        TIPO_DE_MOVIMIENTO = 'Despegue' -- 115.975 -- TAKING ONLY THE DEPARTURES
        AND AEROLINEA_NOMBRE IS NOT NULL
    GROUP BY 
        AEROLINEA_NOMBRE
    ORDER BY
        TOTAL_PASENGERS DESC
    LIMIT 10
)
SELECT 
    *
FROM 
    TOP_TEN_AIR_COMPANIES
    -- DOMESTIC_FLIGHTS_DATA



    
---- # 10
    
WITH RAW_DATA AS (
    SELECT
        FECHA
        ,HORAUTC
        ,CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP) AS DTTM_UTC
        ,FROM_UTC_TIMESTAMP(CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP), 'America/Argentina/Buenos_Aires') AS DTTM_AR -- THIS IS THE DTTM FOR THE ANALYSIS
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,AEROPUERTO
        ,ORIGEN_DESTINO
        ,CASE WHEN AEROLINEA_NOMBRE = '0' THEN NULL ELSE AEROLINEA_NOMBRE END AS AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CASE WHEN AERONAVE = '0' THEN NULL ELSE AERONAVE END AS AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        FLIGHTS_DB.aeropuerto_tabla
)
-- DEDUPLICATING EVENTS
,DEDUPLICATING_DATA AS (
    SELECT 
        *
        ,ROW_NUMBER() OVER(PARTITION BY DTTM_AR, tipo_de_movimiento,  AEROLINEA_NOMBRE, AERONAVE, AEROPUERTO, ORIGEN_DESTINO ORDER BY DTTM_AR, AEROLINEA_NOMBRE, AERONAVE) AS RNN
    FROM 
        RAW_DATA 
    WHERE 
        TO_DATE(DTTM_AR) BETWEEN TO_DATE('2021-01-01') AND TO_DATE('2022-06-30')
)
,FLIGHTS_EVENTS AS (
    SELECT 
        *
    FROM 
        DEDUPLICATING_DATA
    WHERE 
        RNN = 1
) 
,ADD_ORIGIN_AIRPORT_DETAILS AS ( 
    SELECT
        FE.DTTM_UTC
        ,FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,TO_DATE(FE.DTTM_AR) AS FECHA
        ,DATE_FORMAT(FE.DTTM_AR, 'HH:mm') AS HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO AS AEROPUERTO_ORIGEN
        ,O.AEROPUERTO AS AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,O.iata AS ORIGEN_IATA
        ,O.REF AS CIUDAD_ORIGEN
        ,FE.ORIGEN_DESTINO AS AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        FLIGHTS_EVENTS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla O
            ON O.aeropuerto = FE.AEROPUERTO 
)
,ADD_DESTINATION_AIRPORT_DETAILS AS (
    SELECT
        FE.DTTM_UTC
        ,FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,FE.FECHA
        ,FE.HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO_ORIGEN
        ,FE.AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,FE.ORIGEN_IATA
        ,FE.CIUDAD_ORIGEN
        ,FE.AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,D.AEROPUERTO AS AEROPUERTO_DESTINO_CODE
        ,D.IATA AS DESTINO_IATA
        ,D.REF AS CIUDAD_DESTINO
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        ADD_ORIGIN_AIRPORT_DETAILS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla D
            ON D.aeropuerto = FE.AEROPUERTO_DESTINO
)
,DOMESTIC_FLIGHTS_DATA AS (
    SELECT 
        DTTM_UTC
        ,DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,FECHA AS FECHA_AR
        ,HORA AS HORA_AR
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,CASE WHEN ORIGEN_IATA IS NULL THEN AEROPUERTO_ORIGEN ELSE ORIGEN_IATA END AS CODIGO_AEROPUERTO_SALIDA
        ,CIUDAD_ORIGEN AS CIUDAD_DE_SALIDA
        ,CASE WHEN DESTINO_IATA IS NULL THEN AEROPUERTO_DESTINO ELSE DESTINO_IATA END AS CODIGO_AEROPUERTO_ARRIBO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,CIUDAD_DESTINO AS CIUDAD_DE_ARRIBO
        ,AEROLINEA_NOMBRE 
        ,CASE 
            WHEN AERONAVE = 'BO-B737-800' 
                THEN 'BO-737-800' -- 737-800(NG)
            WHEN AERONAVE = 'BO-737-8Q8'
                THEN 'BO-737-8' -- 737 8MAX  
            ELSE 
                AERONAVE
        END AS AERONAVE
        ,PASAJEROS
    FROM 
        ADD_DESTINATION_AIRPORT_DETAILS
)
/*
,TOP_TEN_FLIHTS_WITH_AE AS (
    SELECT
        AEROLINEA_NOMBRE
        ,AERONAVE
        ,SUM(PASAJEROS) AS TOTAL_PASENGERS
    FROM    
        DOMESTIC_FLIGHTS_DATA
    WHERE
        TIPO_DE_MOVIMIENTO = 'Despegue' -- 115.975 -- TAKING ONLY THE DEPARTURES 
        AND AEROLINEA_NOMBRE IS NOT NULL
        --AND aeronave IS NOT NULL
        AND AEROLINEA_NOMBRE = 'AEROLINEAS ARGENTINAS SA' -- /// 3786547
    GROUP BY 
        AEROLINEA_NOMBRE
        ,AERONAVE
    ORDER BY
        TOTAL_PASENGERS DESC
    -- LIMIT 10
)
SELECT 
    *
    -- sum(TOTAL_PASENGERS) 
FROM 
    TOP_TEN_FLIHTS_WITH_AE
*/
,TOP_TEN_PLANES AS (
    SELECT
        AERONAVE
        ,COUNT(*) AS Q_FLIGHTS
    FROM    
        DOMESTIC_FLIGHTS_DATA
    WHERE
        TIPO_DE_MOVIMIENTO = 'Despegue' -- 115.975 -- TAKING ONLY THE DEPARTURES
        AND AERONAVE IS NOT NULL
    GROUP BY 
        AERONAVE
    ORDER BY
        Q_FLIGHTS DESC
    LIMIT 10
)
SELECT 
    *
FROM 
    TOP_TEN_PLANES
    
    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
DROP TABLE flights_db.DOMESTIC_FLIGHTS_DATA;
    
CREATE TABLE flights_db.DOMESTIC_FLIGHTS_DATA AS 
WITH RAW_DATA AS (
    SELECT
        FECHA
        ,HORAUTC
        ,CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP) AS DTTM_UTC
        ,FROM_UTC_TIMESTAMP(CAST(CONCAT(CAST(FECHA AS STRING), ' ', CONCAT(HORAUTC, ':00')) AS TIMESTAMP), 'America/Argentina/Buenos_Aires') AS DTTM_AR -- THIS IS THE DTTM FOR THE ANALYSIS
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,AEROPUERTO
        ,ORIGEN_DESTINO
        ,CASE WHEN AEROLINEA_NOMBRE = '0' THEN NULL ELSE AEROLINEA_NOMBRE END AS AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,CASE WHEN AERONAVE = '0' THEN NULL ELSE AERONAVE END AS AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        FLIGHTS_DB.aeropuerto_tabla
)
-- DEDUPLICATING EVENTS
,DEDUPLICATING_DATA AS (
    SELECT 
        *
        ,ROW_NUMBER() OVER(PARTITION BY DTTM_AR, tipo_de_movimiento,  AEROLINEA_NOMBRE, AERONAVE, AEROPUERTO, ORIGEN_DESTINO ORDER BY DTTM_AR, AEROLINEA_NOMBRE, AERONAVE) AS RNN
    FROM 
        RAW_DATA 
    WHERE 
        TO_DATE(DTTM_AR) BETWEEN TO_DATE('2021-01-01') AND TO_DATE('2022-06-30')
)
,FLIGHTS_EVENTS AS (
    SELECT 
        *
    FROM 
        DEDUPLICATING_DATA
    WHERE 
        RNN = 1
) 
,ADD_ORIGIN_AIRPORT_DETAILS AS ( 
    SELECT
        FE.DTTM_UTC
        ,FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,TO_DATE(FE.DTTM_AR) AS FECHA
        ,DATE_FORMAT(FE.DTTM_AR, 'HH:mm') AS HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO AS AEROPUERTO_ORIGEN
        ,O.AEROPUERTO AS AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,O.iata AS ORIGEN_IATA
        ,O.REF AS CIUDAD_ORIGEN
        ,FE.ORIGEN_DESTINO AS AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        FLIGHTS_EVENTS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla O
            ON O.aeropuerto = FE.AEROPUERTO 
)
,ADD_DESTINATION_AIRPORT_DETAILS AS (
    SELECT
        FE.DTTM_UTC
        ,FE.DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,FE.FECHA
        ,FE.HORA
        ,FE.CLASE_DE_VUELO
        ,FE.CLASIFICACION_DE_VUELO
        ,FE.TIPO_DE_MOVIMIENTO
        ,FE.AEROPUERTO_ORIGEN
        ,FE.AEROPUERTO_ORIGEN_CODE -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,FE.ORIGEN_IATA
        ,FE.CIUDAD_ORIGEN
        ,FE.AEROPUERTO_DESTINO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,D.AEROPUERTO AS AEROPUERTO_DESTINO_CODE
        ,D.IATA AS DESTINO_IATA
        ,D.REF AS CIUDAD_DESTINO
        ,FE.AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,FE.PASAJEROS
    FROM 
        ADD_ORIGIN_AIRPORT_DETAILS FE 
        LEFT JOIN 
            FLIGHTS_DB.aeropuerto_detalles_tabla D
            ON D.aeropuerto = FE.AEROPUERTO_DESTINO
)
,DOMESTIC_FLIGHTS_DATA AS (
    SELECT 
        DTTM_UTC
        ,DTTM_AR -- DTTM FOR THE ANALYSIS. THEY ARE DOMESTIC FLIGHTS
        ,FECHA AS FECHA_AR
        ,HORA AS HORA_AR
        ,CLASE_DE_VUELO
        ,CLASIFICACION_DE_VUELO
        ,TIPO_DE_MOVIMIENTO
        ,CASE WHEN ORIGEN_IATA IS NULL THEN AEROPUERTO_ORIGEN ELSE ORIGEN_IATA END AS CODIGO_AEROPUERTO_SALIDA
        ,CIUDAD_ORIGEN AS CIUDAD_DE_SALIDA
        ,CASE WHEN DESTINO_IATA IS NULL THEN AEROPUERTO_DESTINO ELSE DESTINO_IATA END AS CODIGO_AEROPUERTO_ARRIBO -- TODO: LET SEE IF THIS IS THE IATA CODE
        ,CIUDAD_DESTINO AS CIUDAD_DE_ARRIBO
        ,AEROLINEA_NOMBRE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,AERONAVE -- THIS CHANGE IS ONLY TO THE ANALYSIS
        ,PASAJEROS
    FROM 
        ADD_DESTINATION_AIRPORT_DETAILS
)
SELECT 
    *
FROM 
    DOMESTIC_FLIGHTS_DATA

    
SELECT 
    *
    -- COUNT(*)
FROM 
    flights_db.DOMESTIC_FLIGHTS_DATA;
    
    
    
    
    
    
    
    
    

    